# Generated by Django 5.1 on 2024-08-10 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_option_question_question_correct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='Default Question Title', max_length=255),
        ),
    ]
