# Generated by Django 5.0.7 on 2024-08-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_option_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_option',
            new_name='correct_options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='questions', to='quiz.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice')], default='SC', max_length=2),
        ),
    ]
