# Generated by Django 5.1 on 2024-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_correct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_options',
            field=models.ManyToManyField(related_name='correct_for', to='quiz.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='questions', to='quiz.option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
