# Generated by Django 5.1 on 2024-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_option_question_question_correct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='selected_options',
            field=models.ManyToManyField(to='quiz.option'),
        ),
    ]
