# Generated by Django 5.1 on 2024-08-14 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizattempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizattempt'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='is_correct',
            field=models.BooleanField(),
        ),
    ]
