# Generated by Django 5.1 on 2024-08-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_questionresponse_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
