# Generated by Django 5.1 on 2024-08-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quizattempt_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
